### ISSUE TITLE
Maintain Existing Medium Trust Support

### ISSUE THREAD

**Issue by onesandzeros415** [openstacknetsdk/openstack.net#251]
In the past I created issue #205 as the 1.2 release brought on .NET 3.5 support but not in medium trust environments like the .NET 4.0 library.  In response to issue #205 I've been doing some research with @sharwell and it looks like medium trust for .NET 3.5 will not be able to come to fruition for a few reasons which I will document in issue #205. 

I'm asking that moving forward if it would be possible to integrate medium trust testing for .NET 4.0 into your ci/cd processes?  I'd hate to see the .NET 4.0 library lose this ability as we move forward adding features and functionality from third party libraries, like sharpziplib, and sshnet(which is not medium trust compliant) ect.

If you are able to integrate this into your ci/cd processes you can find the Rackspace Cloud Sites medium trust configuration file here : http://www.rackspace.com/knowledge_center/article/modified-medium-trust-on-cloud-sites

Please let me know your thoughts or concerns on this.

**Comment by carolynvs** [comment]
Per #505 we will not be supporting medium trust environments
