### ISSUE TITLE
Add SuspendServer and ResumeServer to CloudServersProvider.

### ISSUE THREAD

**Issue by ghost** [openstacknetsdk/openstack.net#344]
I suggest that we add SuspendServer and ResumeServer to CloudServersProvider, so we can control each instance from the API.

More information about these features can be found here https://community.rackspace.com/developers/f/7/p/3559/8875#8875.

**Comment by carolynvs** [comment]
Suspend/Resume are operator only actions which aren't really the focus of the SDK at this time. That said, they are straightforward and are good candidates for figuring out how we can support operator actions in the future. So they may make it in anyway, just to demonstrate how operator actions can be added without impacting "userspace". :smile:

**Comment by carolynvs** [comment]
Doh! I was wrong about this (and a few other server actions) being operator only. :blush:  This will be implemented in the 1.6.0 release which is coming next week.

**Comment by carolynvs** [comment]
Fixed by #602
