### ISSUE TITLE
Create a folder in a container?

### ISSUE THREAD

**Issue by robinmls** [openstacknetsdk/openstack.net#449]
I can successfully create a container in Cloud Files via the API, however I'm wondering if there is a way to create a folder in a container via the API?

**Comment by sharwell** [comment]
The Object Storage Service (the general OpenStack name for the Cloud Files product) only includes the following concepts:

* **Container**: This is a top-level grouping (i.e. containers cannot be nested within containers). The name of a container cannot include the `/` character.
* **Object**: This is an item stored within a container. The name of an object *can* include the `/` character.

While you do need to create a container before uploading an object, you do not need to create folders within that object. For example, you could do the following two steps in order without running into problems:

1. Create a new container `MyNewContainer`
2. Upload an object `Name/Name2/Name3.png` to `MyNewContainer`

Based on the fact that an object can include a `/` character in the name, the API provides limited functionality for treating a group of objects as folders, even though the service itself does not store folders. Issue #277 is a feature request for accessing this API functionality in version 1.x. The V2 implementation of the Object Storage service includes support for these features in the initial pull request #448.

**Comment by robinmls** [comment]
Thanks very much for the detailed response, makes sense and works perfectly.
