### ISSUE TITLE
Q: What do I need to know for using the SDK with different clients?

### ISSUE THREAD

**Issue by DonSchenck** [openstacknetsdk/openstack.net#484]
There's the web, Windows, Windows Phone.

Anything specific I need to know when using the SDK to develop clients for those environments?

**Comment by sharwell** [comment]
I don't know of anything that applies here that wouldn't be part of my final answer to #483. I'm closing this as a duplicate, but keeping in mind that I'm not yet done answering #483 please feel free to reopen this if you find it doesn't address all of your questions about clients.
