### ISSUE TITLE
Error while running tests: Could not load Newtonsoft.Json

### ISSUE THREAD

**Issue by DonSchenck** [openstacknetsdk/openstack.net#494]
Several failed tests are reporting the exact same error:

```
Result Message:	
Unit Test Adapter threw exception: 
Could not load file or assembly 'Newtonsoft.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040).
```

**Comment by sharwell** [comment]
I remember seeing an issue like this at some point. Can you point out one of the tests which is causing this problem for you?

**Comment by DonSchenck** [comment]
Very many, but one example is TestAuthenticate.

**Comment by sharwell** [comment]
Note that the V1 and V2 tests use different versions of Json.NET for backward compatibility reasons. If you use the NuGet Package Manager to upgrade the version of Json.NET which is installed in the V1 test assembly to 6.x, then it will fail to load the V1 SDK. If this is the case, you would find that your local copy of the project would differ from [these lines](https://github.com/openstacknetsdk/openstack.net/blob/444ea0661275fb080ff88d9d82eb50f0a6c7e2d4/src/testing/integration/integration.csproj#L53-L54) in this repository.

**Comment by DonSchenck** [comment]
So what is the answer? Upgrade and run the tests for V2? That seems acceptable, because all work going forward is on V2.

**Comment by sharwell** [comment]
I'm not sure what the cause is, but it seems to be resolved if I right click on the two V2 test projects and unload them in Solution Explorer. When working with the V2 code, I load the two V2 test projects and unload the V1 test projects.
