### ISSUE TITLE
What test settings are needed for testing?

### ISSUE THREAD

**Issue by DonSchenck** [openstacknetsdk/openstack.net#495]
Is there a file which has all the necessary Test Settings? What is it, and how is it referenced?

**Comment by DonSchenck** [comment]
Test -> Test Settings
You should have a check mark next to...
...\src\TraceAndTestImpact.testsettings

**Comment by sharwell** [comment]
This is correct. Originally I had this set for a **question**, but I updated it to be **improvement**. Specifically, the project would benefit from the following:

1. Update the developer documentation to explain the process for "setting up a development environment", which includes this issue as well as information obtained from other recently filed issues.
2. If possible, automatically select the correct test settings in a "fresh" clone, so the only time it would end up in an invalid state is if the user explicitly changed something to make it incorrect.
