### ISSUE TITLE
Copied LiveTestConfiguration.json, but now what?

### ISSUE THREAD

**Issue by DonSchenck** [openstacknetsdk/openstack.net#497]
I copied the LiveTestConfigurationTemplate.json file to my \Projects folder, and renamed it to LiveTestConfiguration.json.

However, how do I direct the tests to use, say, the US Rackspace settings?

**Comment by sharwell** [comment]
The tests will use the configuration whose value for `"name"` matches the value for `"selectedCredentials"`.

**Comment by carolynvs** [comment]
Closing v2 enhancements
