### ISSUE TITLE
openstack.net 1.3.4.0 on Medium Trust Environment of .NET 4.0

### ISSUE THREAD

**Issue by raymondzheng1** [openstacknetsdk/openstack.net#505]
Hi, Group/Sam,

I have been using openstack.net 1.3.4.0 for while during development. In my local machine, it worked fine. After I upload it to my website host. I got the security exception ( System.Security.SecurityException: Request for the permission of type 'System.Security.Permissions.SecurityPermission, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' failed.)

My dependency versions from **packages.config** are as follows:

```
<package id="Newtonsoft.Json" version="5.0.8" targetFramework="net40" />
<package id="openstack.net" version="1.3.4.0" targetFramework="net40" />
<package id="SimpleRESTServices" version="1.3.0.1" targetFramework="net40" />
```

I have read relevant post (including #205) related to this but cannot find a solution. 

I suspect that it is the trust level mis-match. My web host is running a medium trust which I cannot change. I have attached the error message below. 

Can you please advise if openstacknet SDK supports medium trust and what do I need to do to fix the issue. 

Thanks heaps.

Raymond

error message:

```
[SecurityException: Request for the permission of type 'System.Security.Permissions.SecurityPermission, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' failed.]
   System.Net.HttpWebRequest.GetRequestStream(TransportContext& context) +6544745
   System.Net.HttpWebRequest.GetRequestStream() +13
   JSIStudios.SimpleRESTServices.Client.<>c__DisplayClass1.<Execute>b__0(HttpWebRequest req) +108
   JSIStudios.SimpleRESTServices.Client.<>c__DisplayClass7.<ExecuteRequest>b__6() +792
   JSIStudios.SimpleRESTServices.Client.RequestRetryLogic.Execute(Func`1 callback, IEnumerable`1 non200SuccessCodes, Int32 retryCount, Nullable`1 retryDelay) +147
   JSIStudios.SimpleRESTServices.Client.RestServiceBase.ExecuteRequest(Uri url, HttpMethod method, Func`3 responseBuilderCallback, Dictionary`2 headers, Dictionary`2 queryStringParameters, RequestSettings settings, Func`2 executeCallback) +295
   JSIStudios.SimpleRESTServices.Client.RestServiceBase.Execute(Uri url, HttpMethod method, Func`3 responseBuilderCallback, String body, Dictionary`2 headers, Dictionary`2 queryStringParameters, RequestSettings settings) +101
   JSIStudios.SimpleRESTServices.Client.RestServiceBase.Execute(Uri url, HttpMethod method, String body, Dictionary`2 headers, Dictionary`2 queryStringParameters, RequestSettings settings) +160
   System.Func`7.Invoke(T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6) +0
   net.openstack.Providers.Rackspace.ProviderBase`1.ExecuteRESTRequest(CloudIdentity identity, Uri absoluteUri, HttpMethod method, Object body, Dictionary`2 queryStringParameter, Dictionary`2 headers, Boolean isRetry, Boolean isTokenRequest, RequestSettings requestSettings, Func`7 callback) +458
   net.openstack.Providers.Rackspace.ProviderBase`1.ExecuteRESTRequest(CloudIdentity identity, Uri absoluteUri, HttpMethod method, Object body, Dictionary`2 queryStringParameter, Dictionary`2 headers, Boolean isRetry, Boolean isTokenRequest, RequestSettings settings) +218
   net.openstack.Providers.Rackspace.<>c__DisplayClass43.<GetUserAccess>b__42() +98
   net.openstack.Core.Caching.<>c__DisplayClassc.<Get>b__4(String k) +10
   System.Collections.Concurrent.ConcurrentDictionary`2.AddOrUpdate(TKey key, Func`2 addValueFactory, Func`3 updateValueFactory) +125
   net.openstack.Core.Caching.UserAccessCache.Get(String key, Func`1 refreshCallback, Boolean forceCacheRefresh) +434
   net.openstack.Providers.Rackspace.CloudIdentityProvider.GetUserAccess(CloudIdentity identity, Boolean forceCacheRefresh) +270
   net.openstack.Providers.Rackspace.ProviderBase`1.GetServiceEndpoint(CloudIdentity identity, String serviceType, String serviceName, String region) +169
   net.openstack.Providers.Rackspace.CloudFilesProvider.GetServiceEndpointCloudFiles(CloudIdentity identity, String region, Boolean useInternalUrl) +31
   net.openstack.Providers.Rackspace.CloudFilesProvider.CreateObject(String container, Stream stream, String objectName, String contentType, Int32 chunkSize, Dictionary`2 headers, String region, Action`1 progressUpdated, Boolean useInternalUrl, CloudIdentity identity) +256
   test.info.emailnotification.testRack() +224
   test.info.emailnotification.Page_Load(Object sender, EventArgs e) +207
   System.Web.Util.CalliEventHandlerDelegateProxy.Callback(Object sender, EventArgs e) +51
   System.Web.UI.Control.OnLoad(EventArgs e) +92
   System.Web.UI.Control.LoadRecursive() +54
   System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint) +6704
   System.Web.UI.Page.ProcessRequest(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint) +245
   System.Web.UI.Page.ProcessRequest() +72
   System.Web.UI.Page.ProcessRequestWithNoAssert(HttpContext context) +21
   System.Web.UI.Page.ProcessRequest(HttpContext context) +58
   ASP.info_emailnotification_aspx.ProcessRequest(HttpContext context) +4
   System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +341
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +69
```

**Comment by raymondzheng1** [comment]
Hi, Group,

Can someone help me here?

Really appreciated. 

Raymond

**Comment by DonSchenck** [comment]
Raymond --

I will track this down.

**Comment by carolynvs** [comment]
Unfortunately we do not support medium trust environments as [it is considered obsolete by Microsoft](http://www.asp.net/aspnet/overview/web-development-best-practices/what-not-to-do-in-aspnet,-and-what-to-do-instead#medium). Here are their [guidelines for migrating from medium trust to a more secure level of isolation](https://support.microsoft.com/en-us/kb/2698981).

Hopefully you can provide that information to your web host and they will work with you to come up with a solution.

**Comment by raymondzheng1** [comment]
Hi, Team,

Thanks for your quick reply. 

I was under the impression that there were some versions of openstack.net SDK supporting medium trust enviroment from the post 

https://github.com/openstacknetsdk/openstack.net/issues/251
https://github.com/openstacknetsdk/openstack.net/issues/205
https://github.com/openstacknetsdk/openstack.net/issues/120

Understand from Carolyn's reply that medium trust enviroment is not longer supported. Just wondering if there is any older version supporting the medium trust. My requirement is simply being able to upload/delete files to Rackspace cloud files. No other fancy operation requirements. Not sure which DLL caused the problem:

<package id="Newtonsoft.Json" version="5.0.8" targetFramework="net40" />
<package id="openstack.net" version="1.3.4.0" targetFramework="net40" />
<package id="SimpleRESTServices" version="1.3.0.1" targetFramework="net40" />

Based on the error log, are you able to advise which DLL caused the problem? Appreciate if you could also advise if there is an older versions of SDK which can be run on Medium trust. 

Lastly, do you know if there is any API I can use to deal with Rackspace cloud files? Based on Rackspace, openstacknetsdk is the only one which they use.

Thanks a lot and look forward to your generous advice. 

Raymond

**Comment by carolynvs** [comment]
I'm new to the project but based on the linked issues, it doesn't sound like we ever accomplished supporting medium trust in any version of the SDK. @sharwell Can you confirm?

**Comment by sharwell** [comment]
That's my understanding as well. We tried for at least a week but I don't remember it ever being successful.

**Comment by raymondzheng1** [comment]
Guys, thanks for the quick response. Seems that I have no other solution than moving away from the web host. 

do you know if there is any other API I can use to deal with Rackspace cloud files? Based on Rackspace, openstacknetsdk is the only one which they use.

Thanks.

**Comment by carolynvs** [comment]
I'm sorry we can't be of more assistance.. I am not aware of another .NET OpenStack SDK but depending on your host and preferences maybe you could use an SDK for another language.

Keep in mind you can always interact directly with the OpenStack API using HTTP.  The [curl examples for the Cloud Files API](https://developer.rackspace.com/docs/cloud-files/getting-started/) demonstrate the proper URLs, verbs and parameters to use. Then you can select a .NET HTTP client such as [RestSharp](http://restsharp.org/) or just use .NET HttpWebRequest.

**Comment by raymondzheng1** [comment]
I think it is the .NET HttpWebRequest which cannot run on Medium trust environment. This is such an essential concept of .Net. It is a pitty. 

Thanks group for your kind help anyway.
