### ISSUE TITLE
AppVeyor build is not reporting status updates

### ISSUE THREAD

**Issue by sharwell** [openstacknetsdk/openstack.net#511]
I noticed that AppVeyor properly [queued a build](https://ci.appveyor.com/project/sharwell/openstack-net/build/1.0.96) for #510, but the status is not being reflected in the pull request. We should double check this integration and make sure it's still configured properly.

**Comment by carolynvs** [comment]
It was queued for a long time and just finally started to build. I'll watch it and see if it's able to update the pull request status.

**Comment by carolynvs** [comment]
I'm not sure what caused the long queue time but the webhook is working just fine. The build status was reported back successfully to GitHub.

**Comment by sharwell** [comment]
I'm still not seeing a status update for #510. Compare this to the way #507 appears (a previous build success), or #504 (a previous build failure).

**Comment by carolynvs** [comment]
Doh, yeah I see what you mean now.  I am guessing the issue is that the appveyor build is on your personal account and uses your personal github api token? Maybe we can move the build into an AppVeyor organization instead so that it's not tied to any particular user.

**Comment by carolynvs** [comment]
PR #512 fixes this issue. GH is now back in sync with AppVeyor.
