### ISSUE TITLE
GetAccountMetaData returns no values

### ISSUE THREAD

**Issue by pedershk** [openstacknetsdk/openstack.net#558]
Trying to do this:
```
 var accountMetadata = _cloudFilesProvider.GetAccountMetaData();
```
to get a TempKey for use with CreateFormPostUrl(). However, the accountMetadata Dictionary<string,string> always returns no values (the count is 0). 

A call to
```
 var accountHeaders = _cloudFilesProvider.GetAccountHeaders();
```
Does return data (13 key/value pairs in total) - and other methods run too on the cloud files provider, so I'm "connected".

Any way to debug this further?

**Comment by carolynvs** [comment]
@pedershk Apologies for the late reply, I was unplugged and on vacation last week. I'll take a look and get back to you hopefully today with a workaround or bug report.

**Comment by carolynvs** [comment]
@pedershk It seems that the temp url key can be unset on an account, though my Rackspace account had one set by default. I will investiage to see if this is just a difference between Rackspace and vanilla OpenStack or something else :smile: 

You may find it helpful to read more about working with [OpenStack Temp URLs](http://docs.openstack.org/kilo/config-reference/content/object-storage-tempurl.html).

In the meantime, here is some code which will populate your key and get you up and running with temp URLs.

```csharp
var identity = new CloudIdentity
{
    Username = "{username}",
    APIKey = "{api-key}"
};

// Manually set the temp url key
var tempUrlKey = Guid.NewGuid().ToString();

var cloudFilesProvider = new CloudFilesProvider(identity);
cloudFilesProvider.UpdateAccountMetadata(new Dictionary<string, string> { {CloudFilesProvider.TempUrlKey, tempUrlKey} });

// Verify that the temp url key is now populated
var metadata = cloudFilesProvider.GetAccountMetaData();
Debug.Assert(metadata.ContainsKey(CloudFilesProvider.TempUrlKey));
Debug.Assert(tempUrlKey.Equals(metadata[CloudFilesProvider.TempUrlKey]));
```

**Comment by pedershk** [comment]
No problems. Let me know if you need any more data.

**Comment by carolynvs** [comment]
I've confirmed that this always need to be manually set first (this is a one-time setup) before you can use it.
