### ISSUE TITLE
The type initializer for 'OpenStack.OpenStackNet' threw an exception.

### ISSUE THREAD

**Issue by sanjaykr** [openstacknetsdk/openstack.net#565]
My application is hosted on Rackspace Cloud sites and using net.openstack.Core.Domain lib.
While uploading the images(.png or gif) or any kind of content. I am getting "The type initializer for 'OpenStack.OpenStackNet' threw an exception." error. 
Please advice.

**Comment by DonSchenck** [comment]
Are you specifying the content-type?

**Comment by sanjaykr** [comment]
Yes, while running the code from my local workstation it works well but when same code runs on rackspace cloud sites it gives the above error.

**Comment by DonSchenck** [comment]
Remove the content-type and let OpenStack automatically determine the type; that should solve the issue.

**Comment by carolynvs** [comment]
@sanjaykr Has this issue been resolved? I just pushed out a patch, 1.5.0.2, which addressed a problem that may be related. If you are still having trouble, please comment back and I'll reopen this issue.
