### ISSUE TITLE
Outdated Newtonsoft.Json reference

### ISSUE THREAD

**Issue by mnbeer** [openstacknetsdk/openstack.net#614]
Anything preventing the project from referencing Newtonsoft.Json 8+? The current dependency is more than a year-old and that can force some creative juggling when adding openstack.net to apps/libraries requiring newer Newtonsoft.Json versions.

**Comment by carolynvs** [comment]
I can't recall anymore why I pinned the json.net dependency at `6.*`. I'll try updating it and see what explodes. :smile:

**Comment by mnbeer** [comment]
Thanks and good luck!

**Comment by carolynvs** [comment]
It's looking good. I need to do a bit more pre-release testing, but hope to put out a new version today.

**Comment by mnbeer** [comment]
That's great and will likely prevent many headaches (not just mine). Thanks for jumping on so quickly.

**Comment by carolynvs** [comment]
I've published version [1.7.0-beta.2 to nuget.org](https://www.nuget.org/packages/openstack.net/1.7.0-beta0002). Would you mind trying that out and letting me know if you run into any issues? In one of my projects, I had to add an assembly binding redirect manually but I thought nuget was smart enough to add those automatically when a package is udpated...

If it all looks good, then this will go out officially in the 1.7.0 release next week.

**Comment by mnbeer** [comment]
Thanks. I'll give it a shot and let you know. I'm upgrading from v 1.3.4 so I may have a host of other breaking changes to wade through.

**Comment by mnbeer** [comment]
Things seem to be working fine for me with the caveat that I don't have sophisticated needs. I am only calling CreateObject, CopyObject, GetObject, and DeleteObject. The calls all work without any alteration of code; that makes me happy.

**Comment by carolynvs** [comment]
Thanks, that's good enough for me! I'll report back here when 1.7.0 releases.

**Comment by carolynvs** [comment]
@mnbeer Thanks for bringing up this issue. [v1.7.0](https://github.com/openstacknetsdk/openstack.net/releases/v1.7.0) with support for json.net 6-8 is available on nuget.

**Comment by mnbeer** [comment]
Nice. Thanks.

Matthew Nicholson Beer
The Foundry Software Development Co.
(314) 529-1455
matthew.beer@foundrysoftware.com
