### ISSUE TITLE
Support for Newtonsoft.Json 9.x

### ISSUE THREAD

**Issue by Gonnagle** [openstacknetsdk/openstack.net#625]
Currently the package depends on Newtonsoft.Json 6.0.1 >= x < 9.0. This causes problems on our project as another packet needs version >= 9.0.1. 

According to the [realease notes](https://github.com/JamesNK/Newtonsoft.Json/releases/tag/9.0.1) version 9.0.1 does not introduce any breaking changes (don't know why the major number is bumped up in this case...).  I quickly tested to upgrade openstack.net to use 9.0.1 and at least the UnitTests seemed to pass just fine.

Could the supported version range be increased to cover 9.x versions?

**Comment by Gonnagle** [comment]
Created a pull request that addresses the nuspec part.

Additionally the the paket.dependencies could be updated to match the range defined in nuspec (`6.0.1 >= x < 10.0`). Now it is `~> 6.0` which I believe resolves to `6.0 >= x < 7.0`? I have no prior experience with Paket so I did not modify this on the pull request.

**Comment by carolynvs** [comment]
Yeah, it's frustrating that json.net doesn't follow semver! 😄 At one point, their v9 beta package only supported .net core, so I was excluding it.

I'll get that updated and ping back when the updated NuGet package is available.

Thanks! 🍰

**Comment by carolynvs** [comment]
FYI, the paket depency isn't a range because of runtime version dependencies and assembly binding redirects. tldr: building against the lowest version of a dependency means consumers don't require assembly binding redirects unless they upgrade the dependency themselves.

**Comment by carolynvs** [comment]
Thank you for the fix! Your changes are included in the OpenStack.NET [v1.7.3](https://github.com/openstacknetsdk/openstack.net/releases/tag/v1.7.3).

**Comment by Gonnagle** [comment]
Thank you for the fast update! :+1:

Thank you also for explaining the paket dependency. Going to explore Paket more as it seems it might ease up the pain we currently have with managing our nuget dependencies.

**Comment by carolynvs** [comment]
FYI, I am building against the lowest version of my dependencies not because of paket, but because when people used nuget to install this package, the generated app.config's assembly binding redirects were incorrect and required hand editing. The generated version range wasn't including the version that I compiled against, causing runtime errors. 

Just wanted to exonerate paket here, as it's all caused by nuget. 😄 See https://github.com/openstacknetsdk/openstack.net/issues/623 for how the bug manifested.

**Comment by jamespedid** [comment]
I'm having issues with this. I have referenced Newtonsoft version 9 in my project that also uses openstack.net; at runtime I'm receiving the following error: 

````
Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)\r\n   at net.openstack.Core.Providers.OpenStackIdentityProvider.<>c__DisplayClass4_0.<GetUserAccess>b__0()\r\n   at net.openstack.Core.Caching.UserAccessCache.<>c__DisplayClass2_0.<Get>b__0(String k)\r\n   at System.Collections.Concurrent.ConcurrentDictionary`2.AddOrUpdate(TKey key, Func`2 addValueFactory, Func`3 updateValueFactory)\r\n   at net.openstack.Core.Caching.UserAccessCache.Get(String key, Func`1 refreshCallback, Boolean forceCacheRefresh)\r\n   at net.openstack.Core.Providers.OpenStackIdentityProvider.GetUserAccess(CloudIdentity identity, Boolean forceCacheRefresh)\r\n   at net.openstack.Providers.Rackspace.CloudIdentityProvider.Authenticate(CloudIdentity identity)\r\n
````

This is being run in the following sense:

I have an ASP.NET core application (the kind that uses the .NET Framework and not .NET core). That application is running an executable to do a file conversion process (recommended by the vendor for file conversion). That executable uses Newtonsoft version 9, along with the class library that it references, that references Newtonsoft version 9 and Openstack. 

I'm wondering if the version lock of Newtonsoft at 6.0.8 in the .paket.lock file has anything to do this this, or if you know of any other work arounds to get this to work.

**Comment by carolynvs** [comment]
Most likely your assembly binding redirects isn't correct. It should have something like this in it (untested but this is the right place to poke around):

```
<configuration>
    <startup> 
        <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.5.2" />
    </startup>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-9.0.0.0" newVersion="9.0.0.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>
```

**Comment by jamespedid** [comment]
Thanks for the help, but I tried every permutation of doing that, in every config file that I could find, but it still isn't biting.

When I run it in debug on the development machine, it is working.

But then I'm packaging it up as a Web Deploy Package and then importing it into IIS. I'm getting the binding error as a loading error.

If I build the assembly on the server, it also works.

There must be something wrong with the deploy process that prevents this from working.

**Comment by carolynvs** [comment]
Sorry, this is beyond my ability to help troubleshoot...

**Comment by snello** [comment]
@jamespedid did you find a solution to your problem here?  I'm facing the same issue and would gratefully hear your thoughts - happy to do it out of band as the solution may not be directly related to the issue raised here.
