### ISSUE TITLE
Intermediate certificate property has the wrong name in json

### ISSUE THREAD

**Issue by gdau** [openstacknetsdk/openstack.net#629]
I'm busy integrating this API with letsencrypt to auto-provision certs to a rackspace load balancer and am having issues using the ssltermination endoint.

When I inspect the traffic, I can see the intermediate certificate is being passed with the name "intermediatecertificate" but according to the Rackspace docs it should be "intermediateCertificate" (with a capital C). This is causing requests to update SSL termination to fail. It is the UpdateSslConfigurationAsync method I am using from the CloudLoadBalancerProvider class.

FYI the typo is on line 51 of LoadBalancerSslConfiguration.cs.

Thanks!

g

**Update: I can confirm changing this as described above has fixed my error.**

**Comment by carolynvs** [comment]
Thanks for reporting the bug and identifying the fix! I'll try to get an updated nuget package out today.

**Comment by carolynvs** [comment]
A fix for this is included in [OpenStack.NET v1.7.5](https://www.nuget.org/packages/openstack.net/1.7.5) which you can download from nuget.
