### ISSUE TITLE
CloudFilesProvider.GetObject() call makes 2 calls to get new token each time

### ISSUE THREAD

**Issue by harshanandmv** [openstacknetsdk/openstack.net#634]
CloudFilesProvider.GetObject() call makes 2 calls to get new token each time. 
If I call the GetObject() again, there are 2 new calls to get the new token again, which means caching the token isn't working. This is causing a huge performance hit when we use this method.  I have verified this with a standalone program which does the GetObject call (with Fiddler to monitor the calls to Swift).

**Comment by carolynvs** [comment]
Which version of the SDK are you using? I just fixed a bug with token caching in [v1.7.6](https://github.com/openstacknetsdk/openstack.net/releases/v1.7.6).
