### ISSUE TITLE
NuGet issues

### ISSUE THREAD

**Issue by AaronLayton** [openstacknetsdk/openstack.net#635]
I am trying to install this from NuGet but the Dependency required it a specific version instead of a minimum version of `Marvin.JsonPatch.Signed`

Marvin.JsonPatch.Signed v`0.7.0` is no longer published in NuGet and the minimum is `0.9.0`

![2016-10-18_15h03_57](https://cloud.githubusercontent.com/assets/694964/19480992/63e82900-9544-11e6-9097-5ef1d0bb9481.png)

**Comment by AaronLayton** [comment]
I figured my issue - csproj file was messed up also. 
Leaving this note though as surely it should be min version of `0.7.0` still

**Comment by carolynvs** [comment]
Marvin.JsonPatch.Signed 0.7.0 is still published on NuGet, [https://www.nuget.org/packages/Marvin.JsonPatch.Signed/0.7.0](https://www.nuget.org/packages/Marvin.JsonPatch.Signed/0.7.0). I'm not sure what the problem is but feel free to add more comments if you figure it out.
