### ISSUE TITLE
the Newtonsoft.Json version need to be upgraded to 10.x

### ISSUE THREAD

**Issue by liu-hongwei** [openstacknetsdk/openstack.net#651]
the Newtonsoft.Json version required in openstack release 1.7.7 is still old, need to upgrade to 10.x

**Comment by johnrutherford** [comment]
I've created pull request #653 to address this.

**Comment by dwalleck** [comment]
This PR was merged, so this issue should be resolved. Please re-open this if it is not the case.

**Comment by johnrutherford** [comment]
@dwalleck, when can we get a new release to NuGet for this?

**Comment by Gonnagle** [comment]
This is causing some really annoying dependency conflicts for us as well. So really would like to see a release with this in it.
